<?php

namespace Repo\Util\Command\Repositories;

use Repo\Util\View\Packages\All;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Show extends Command {
    protected function configure() {
        $this->setName("repositories:show");
        $this->addOption('type');
        $this->addOption('name');
        $this->addArgument('tokens');
        $this->setDescription("Find / find installable packages");
        $sSystemName = function_exists('getSiteSettings') ? getSiteSettings()['system_name'] : 'Innovation App';
        $this->setHelp(<<<EOT
Packagist is the default way of sharing components, libraries or pieces of code in the PHP landscape. This command 
allows you to search for installable packages from the Packagist API that are specifically written for installation in 
{$sSystemName}. For more info refer to the Components or Plugins section of the documentation.  
EOT
        );
    }

    protected function initialize(InputInterface $input, OutputInterface $output) {
        All::show($output);

        parent::initialize($input, $output); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output) {

        return Command::SUCCESS;
    }

}
