<?php

namespace Repo\Util\Command\Compare;

use Repo\Util\Model\PackageManager;
use Repo\Util\View\Packages\All;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Formatter\OutputFormatterStyle;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SiteJson extends Command {
    protected function configure() {
        $this->setName("compare:site-json");
        $this->addOption('type');
        $this->addOption('name');
        $this->addArgument('tokens');
        $this->setDescription("Compare all the site.json files");
    }

    protected function initialize(InputInterface $input, OutputInterface $output) {
        parent::initialize($input, $output); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output) {
        $outputStyle = new OutputFormatterStyle('white', 'blue', ['bold', 'blink']);
        $output->getFormatter()->setStyle('bold', $outputStyle);

        $oPackageManager = new PackageManager();
        $oPackageIterator = $oPackageManager->getAll();

        $iMissingPackageCount = 0;
        foreach ($oPackageIterator as $oPackage)
        {
            if(!$oPackage->isInstalled())
            {
                $iMissingPackageCount++;
            }

        }

        $output->writeln("<question><bold>$iMissingPackageCount</bold> new packages found, shall we clone them?</question>");

        return Command::SUCCESS;
    }

}
